import { IProduct } from "../models/product/product.model";

export const products: IProduct[] = [
  {
    name: "Free Shirt",
    category: "Shirts",
    image: "/images/shirt1.jpg",
    price: 70,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A popular shirt",
    createdOn: new Date(),
  },
  {
    name: "Fit Shirt",
    category: "Shirts",
    image: "/images/shirt2.jpg",
    price: 80,
    brand: "Addidas",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A popular shirt",
    createdOn: new Date(),
  },
  {
    name: "Slim Shirt",
    category: "Shirts",
    image: "/images/shirt3.jpg",
    price: 90,
    brand: "Raymond",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A popular shirt",
    createdOn: new Date(),
  },
  {
    name: "Gold Pants",
    category: "Pants",
    image: "/images/pants1.jpg",
    price: 90,
    brand: "Oliver",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "Smart looking pants",
    createdOn: new Date(),
  },
  {
    name: "Fit Pants",
    category: "Pants",
    image: "/images/pants2.jpg",
    price: 95,
    brand: "Zara",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A popular Pants",
    createdOn: new Date(),
  },
  {
    name: "Classic Pants",
    category: "Pants",
    image: "/images/pants3.jpg",
    price: 100,
    brand: "Casely",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A popular Pants",
    createdOn: new Date(),
  },
];
